name: tiwentianbao

on:
  workflow_dispatch: #在actions界面点击即可运行
  schedule:
    - cron: '0 3,4 * * *'  
  #Runs at 03:00 and 04:00 UTC every day.beijing +8  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run:  pip install -r ./requirements.txt  #此处为安装依赖包
    - run: python ./temperature.py  #此处为python代码的文件名
